FROM python:3.8-slim-buster

WORKDIR /app/

COPY . /app/

RUN pip install --upgrade pip setuptools wheel
RUN pip install pipenv
RUN pipenv install

ARG REDIS_URL
ARG META_KEY
ARG DB_USER
ARG DB_PASS
ARG DB_HOST
ARG DB_NAME
ARG DATABASE_URL
ARG SCHEDULE_JOBS
ARG FEEDS_BASEURL
ARG FEEDS_PASSWORD
ARG FEEDS_USEAREMAIL
ARG SECRET_KEY

ENV FLASK_ENV=production
ENV REDIS_URL=$REDIS_URL
ENV META_KEY=$META_KEY
ENV DB_USER=$DB_USER
ENV DB_PASS=$DB_PASS
ENV DB_HOST=$DB_HOST
ENV DB_NAME=$DB_NAME
ENV DATABASE_URL=$DATABASE_URL
ENV SCHEDULE_JOBS=$SCHEDULE_JOBS
ENV FEEDS_BASEURL=$FEEDS_BASEURL
ENV FEEDS_PASSWORD=$FEEDS_PASSWORD
ENV FEEDS_USEAREMAIL=$FEEDS_USEAREMAIL
ENV SECRET_KEY=$SECRET_KEY

RUN echo $REDIS_URL
RUN chmod 777 ./entrypoint.sh

ENTRYPOINT ["sh", "-c", "./entrypoint.sh"]
# CMD ["gunicorn", "wsgi:app", "--bind", "0.0.0.0:5000"]
