"""Add region

Revision ID: 0db7ed089b1c
Revises: 5102f22d631e
Create Date: 2021-11-19 17:28:02.970537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db7ed089b1c'
down_revision = '5102f22d631e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('region', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'region')
    # ### end Alembic commands ###
