"""newsfeed_article

Revision ID: f9063b3dd442
Revises: 04b495d16999
Create Date: 2021-11-12 12:20:30.543042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9063b3dd442'
down_revision = 'fa149bbac81a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('article_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('article_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    # ### end Alembic commands ###
