"""empty message

Revision ID: fa149bbac81a
Revises: 04b495d16999
Create Date: 2021-11-12 20:25:24.331975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa149bbac81a'
down_revision = '04b495d16999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_jwt_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jwt_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expire_time', sa.DateTime(), nullable=False),
    sa.Column('refresh_expire_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('jwt_token'),
    sa.UniqueConstraint('refresh_token')
    )
    op.add_column('users', sa.Column('google_user_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_user_token', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['google_user_id'])
    op.create_unique_constraint(None, 'users', ['google_user_token'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'google_user_token')
    op.drop_column('users', 'google_user_id')
    op.drop_table('user_jwt_token')
    # ### end Alembic commands ###
