"""Add Affliates table

Revision ID: fe4136ab5212
Revises: f9063b3dd442
Create Date: 2021-11-18 16:31:28.394370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe4136ab5212'
down_revision = 'f9063b3dd442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'user_jwt_token', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_jwt_token', type_='unique')
    op.drop_table('affiliates')
    # ### end Alembic commands ###
